nfl_rushing/models.py
from nfl_rushing.database import db


class Player(db.Model):
    __tablename__ = 'players'

    name = db.Column(db.Text, primary_key=True)
    team = db.Column(db.Text)
    position = db.Column(db.Text)
    attempts = db.Column(db.Integer)
    attempts_per_game = db.Column(db.Float)
    yards = db.Column(db.Integer)
    yards_per_carry = db.Column(db.Float)
    yards_per_game = db.Column(db.Float)
    touchdowns = db.Column(db.Integer)
    longest_run = db.Column(db.Integer)
    long_is_touchdown = db.Column(db.Boolean)
    first_downs = db.Column(db.Integer)
    first_down_percentage = db.Column(db.Float)
    over_twenty = db.Column(db.Integer)
    over_forty = db.Column(db.Integer)
    fumbles = db.Column(db.Integer)

    def to_table_data(self):
        return [
            self.name,
            self.team,
            self.position,
            self.attempts,
            self.attempts_per_game,
            self.yards,
            self.yards_per_carry,
            self.yards_per_game,
            self.touchdowns,
            self.longest_run if not self.long_is_touchdown else f'{self.longest_run}T',
            self.first_downs,
            self.first_down_percentage,
            self.over_twenty,
            self.over_forty,
            self.fumbles
        ]

    @staticmethod
    def to_database_model(json):
        longest_run = str(json['Lng'])
        long_is_touchdown = 'T' in longest_run
        longest_run = int(longest_run.replace('T', ''))

        return Player(
            name=json['Player'],
            team=json['Team'],
            position=json['Pos'],
            attempts=json['Att'],
            attempts_per_game=json['Att/G'],
            yards=json['Yds'],
            yards_per_carry=json['Avg'],
            yards_per_game=json['Yds/G'],
            touchdowns=json['TD'],
            longest_run=longest_run,
            long_is_touchdown=long_is_touchdown,
            first_downs=json['1st'],
            first_down_percentage=json['1st%'],
            over_twenty=json['20+'],
            over_forty=json['40+'],
            fumbles=json['FUM'])

nfl_rushing/app.py
import json

from flask import Flask

from nfl_rushing.database import db
from nfl_rushing.views import bp
from nfl_rushing.models import Player


def create_app():
    """ Create the flask application

    This method is responsible for creating the root flask
    app object, configuring the use of an in-memory sqlite
    database, registering the blueprints (routes), and lastly
    initializing and loading the data into the database.

    Since this app uses an in-memory database the schema can
    be created and the data can be loaded on startup without
    issue.
    """
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.register_blueprint(bp)

    __initialize_db(app)
    __load_json_data()
    return app


def __initialize_db(app):
    db.init_app(app)
    app.app_context().push()
    db.create_all()


def __load_json_data():
    with open('rushing.json', 'r') as f:
        rushing_data = json.load(f)
    players = [Player.to_database_model(d) for d in rushing_data]
    db.session.add_all(players)
    db.session.commit()

nfl_rushing/views.py
import csv
import os

from flask import Blueprint, render_template, request, send_file

from nfl_rushing.columns import columns, get_order_by
from nfl_rushing.models import Player

bp = Blueprint('bp', __name__)


@bp.route('/')
def index():
    """ Endpoint to render the queried player data in the browser.

    Given the sorting, filtering, and paging query parameters, we retrieve a
    paginated set of data from the database and use the method 'render_template'
    render our html page with the player data in the table.

    See `nfl_rushing/templates/index.html` for the templated html.
    """
    sort = __get_sort_query_param()
    page = __get_page_query_param()
    name = __get_name_query_param()

    players = __get_base_query(name, sort).paginate(page, 15)

    return render_template('index.html', columns=columns.values(), players=players, name=name, sort=sort, page=page)


@bp.route('/download')
def download():
    """Endpoint to download the queried data as a csv file.

    Given the sorting and filtering query parameters, we retrieve all of the
    matching rows from the database and write them to a csv file to be returned
    to the requesting user.

    To avoid taking up extra space with duplicate files and making unnecessary
    database calls, this method checks if a file of the same name already exists
    and skips the part where it needs to query player data and write it to a file.

    This is possible because the data in this application is read only so it never
    changes and the sorting/filtering parameters can be used to indicate what
    data was written to a file in the form 'data-sort-{sort}-name-{name}.csv' where
    the sort or name sections are ommitted if the query parameter was not provided.

    One thing to note is that we have a `filepath` variable and a `base_file_path`
    variable because Flask looks for the files in a different place than they are
    written when using `with open(..)` if they use the same file name. The filepath
    variable is ued by Flask since it looks in the `nfl_rushing` directory by default
    while checking the existence and writing a new file requires the `base_filepath`
    variable which is pre-pended with the `nfl_rusing/` directory.
    """
    sort = __get_sort_query_param()
    name = __get_name_query_param()

    filepath, base_filepath = __get_file_paths(sort, name)

    if not os.path.exists(base_filepath):
        players = __get_base_query(name, sort).all()
        with open(base_filepath, 'w') as f:
            writer = csv.writer(f)
            writer.writerow([c.display for c in columns.values()])
            writer.writerows([player.to_table_data() for player in players])
    return send_file(filepath, as_attachment=True, max_age=-1)


def __get_file_paths(sort, name):
    filepath = 'reports/data'
    if sort:
        filepath += f'-sort-{sort}'
    if name:
        filepath += f'-name-{name}'
    filepath += '.csv'

    base_file_path = f'nfl_rushing/{filepath}'
    os.makedirs(os.path.dirname(base_file_path), exist_ok=True)
    return filepath, base_file_path


def __get_sort_query_param():
    return request.args.get('sort', default=None, type=str)


def __get_name_query_param():
    return request.args.get('name', default=None, type=str)


def __get_page_query_param():
    return request.args.get('page', default=1, type=int)


def __get_base_query(name, sort):
    base_query = Player.query.order_by(get_order_by(sort))
    if name:
        base_query = base_query.filter(Player.name.contains(name))
    return base_query

nfl_rushing/templates/index.html
<html>

<head>
  <title>2016 NFL Rushing Statistics</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!-- Stylesheet -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
  
  <!-- Initialize Tooltips -->
  <script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();  
    });
  </script>
</head>

<body>
  <div class="container">
    <div id="title-row" class="row justify-content-center">
      <h1>2016 NFL Rushing Statistics</h1>
    </div>

    <div title="filter-row" class="row justify-content-between">
      <div class="col-auto">
        <form method="GET">
          {% set placeholder = '' if name is none else name %}
          Filter by name: <input id="name-filter" name="name" value="{{ placeholder }}" maxlength=100>
          <input id="submit-button" type="submit" value="Submit" class="btn btn-primary btn-sm">
          <a href="{{ url_for('bp.index', sort=sort, page=page) }}" class="btn btn-secondary btn-sm">Clear</a>
        </form>
      </div>
      <div class="col-auto">
        <a href="{{ url_for('bp.download', sort=sort, name=name) }}" class="btn btn-secondary btn-sm flo">Download</a>
      </div>
    </div>

    <div id="table-row" class="row h-75">
      <div class="table-responsive h-100">
        <table class="table">
          <thead class="thead-light">
            <tr>
              {% for column in columns %}
              <th>
                <a href="{{ url_for('bp.index', sort=column.get_sort(sort), name=name, page=page) }}" data-toggle="tooltip" title="{{ column.tooltip }}">
                  {{ column.get_display(sort) }}
                </a>
              </th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for player in players.items %}
            <tr>
              {% for player_data in player.to_table_data() %}
              <td>{{ player_data }}</td>
              {% endfor %}
            </tr>
            {% else %}
            <tr>
              <td class="text-center" colspan="15">No players found matching "{{ name }}"</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div id="paging-row" class="row justify-content-center">
      <div class="col-xl-1 col-lg-1 col-md-2 col-sm-2 col-2 text-center">
        {% if players.has_prev %}
        <a href="{{ url_for('bp.index', sort=sort, name=name, page=1) }}" class="btn btn-primary btn-sm">First</a>
        {% endif %}
      </div>
      <div class="col-xl-1 col-lg-1 col-md-2 col-sm-2 col-2 text-center">
        {% if players.has_prev %}
        <a href="{{ url_for('bp.index', sort=sort, name=name, page=players.prev_num) }}"
          class="btn btn-primary btn-sm">Prev</a>
        {% endif %}
      </div>
      <div class="col-xl-1 col-lg-1 col-md-2 col-sm-2 col-2 text-center">
        {% if (sort is not none) or (name is not none) %}
        <a href="{{ url_for('bp.index') }}" class="btn btn-secondary btn-sm">Reset</a>
        {% endif %}
      </div>
      <div class="col-xl-1 col-lg-1 col-md-2 col-sm-2 col-2 text-center">
        {% if players.has_next %}
        <a href="{{ url_for('bp.index', sort=sort, name=name, page=players.next_num) }}"
          class="btn btn-primary btn-sm">Next</a>
        {% endif %}
      </div>
      <div class="col-xl-1 col-lg-1 col-md-2 col-sm-2 col-2 text-center">
        {% if players.has_next %}
        <a href="{{ url_for('bp.index', sort=sort, name=name, page=players.pages) }}"
          class="btn btn-primary btn-sm">Last</a>
        {% endif %}
      </div>
    </div>
  </div>
</body>

</html>